### ISSUE TITLE
Grant types cannot be changed

### ISSUE THREAD

**Issue by miltonlaufer** [rhertogh/yii2-oauth2-server#10]
Hi! Thank you for this library, it's exactly what I needed. 
I'm having a problem: I set up the grant types to accept refresh tokens, but for some reason they are not appearing as accepted grant types.

### What steps will reproduce the problem?

This is my module configuration:

```
use rhertogh\Yii2Oauth2Server\interfaces\components\openidconnect\scope\Oauth2OidcClaimInterface;
use rhertogh\Yii2Oauth2Server\interfaces\components\openidconnect\scope\Oauth2OidcScopeInterface;
use rhertogh\Yii2Oauth2Server\Oauth2Module;


return [
    'class'                       => rhertogh\Yii2Oauth2Server\Oauth2Module::class,
    'identityClass'               => app\models\User::class,
    'serverRole' => 1, //Authorization server role
     'privateKey'                  => file_get_contents('/app/KEYS/private.key'),
    'publicKey'                   => file_get_contents('/app/KEYS/public.key'),
    'privateKeyPassphrase'        => null,
    'codesEncryptionKey'          => env('YII2_OAUTH2_SERVER_CODES_ENCRYPTION_KEY'),
    'storageEncryptionKeys'       => 
              ['2023-02-10' => env('YII2_OAUTH2_SERVER_STORAGE_ENCRYPTION_KEY'),
    ],
    'clientAuthorizationView'     => '@app/views/authorize-client/authorize-client',
    'defaultStorageEncryptionKey' => '2023-02-10',
    'openIdConnectScopes'         => [
        Oauth2OidcScopeInterface::OPENID_CONNECT_SCOPE_OPENID,
        Oauth2OidcScopeInterface::OPENID_CONNECT_SCOPE_EMAIL,
        Oauth2OidcScopeInterface::OPENID_CONNECT_SCOPE_ADDRESS,
        Oauth2OidcScopeInterface::OPENID_CONNECT_SCOPE_PHONE,
        Oauth2OidcScopeInterface::OPENID_CONNECT_SCOPE_PROFILE => [
            // Oauth2OidcClaimInterface::OPENID_CONNECT_CLAIM_GIVEN_NAME => 'first_name',
            Oauth2OidcClaimInterface::OPENID_CONNECT_CLAIM_EMAIL => 'email',
            'username',
        ],
    ],
    'grantTypes'                  => [
        Oauth2Module::GRANT_TYPE_AUTH_CODE,
        Oauth2Module::GRANT_TYPE_REFRESH_TOKEN,
    ],
    'migrationsNamespace'         => 'app\\migrations\\oauth2',
    'enableOpenIdConnect'         => true,
];
```

### What is the expected result?

When I check "/.well-known/openid-configuration", I get this

![image](https://user-images.githubusercontent.com/3741623/219688897-59bb9c95-37dc-4651-a512-7774a75db2dc.png)

### What do you get instead?

The refresh token as an accepted grant type (for instance, with google's OpenID I get this):

![image](https://user-images.githubusercontent.com/3741623/219689072-7ae280f8-f084-4273-b04d-57479fae3906.png)

### Additional info

| Q                         | A
| ------------------------- | ---
| Yii-Oauth2-Server version | 1.0.0-alpha-6
| Yii version               |   2.0.48-dev.
| PHP version               |  7.4.33
| Operating system          |Debian GNU/Linux 11 (bullseye)

### Yii-Oauth2-Server Configuration
(created with the `yii oauth2/debug/config` command)
<pre>Configuration:
╔═══════════════════════════════════════════════════════╤═════════════════════════════════════════════╗
║ Setting                                               │ Value                                       ║
╟───────────────────────────────────────────────────────┼─────────────────────────────────────────────╢
║ serverRole                                            │ 1 (Authorization Server)                    ║
╟───────────────────────────────────────────────────────┼─────────────────────────────────────────────╢
║ privateKey                                            │ [SET]                                       ║
╟───────────────────────────────────────────────────────┼─────────────────────────────────────────────╢
║ privateKeyPassphrase                                  │ [NOT SET]                                   ║
╟───────────────────────────────────────────────────────┼─────────────────────────────────────────────╢
║ publicKey                                             │ [SET]                                       ║
╟───────────────────────────────────────────────────────┼─────────────────────────────────────────────╢
║ codesEncryptionKey                                    │ [SET]                                       ║
╟───────────────────────────────────────────────────────┼─────────────────────────────────────────────╢
║ storageEncryptionKeys                                 │ [SET]                                       ║
╟───────────────────────────────────────────────────────┼─────────────────────────────────────────────╢
║ defaultStorageEncryptionKey                           │ 2023-02-10                                  ║
╟───────────────────────────────────────────────────────┼─────────────────────────────────────────────╢
║ identityClass                                         │ app\models\User                             ║
╟───────────────────────────────────────────────────────┼─────────────────────────────────────────────╢
║ urlRulesPrefix                                        │ oauth2                                      ║
╟───────────────────────────────────────────────────────┼─────────────────────────────────────────────╢
║ authorizePath                                         │ authorize                                   ║
╟───────────────────────────────────────────────────────┼─────────────────────────────────────────────╢
║ accessTokenPath                                       │ access-token                                ║
╟───────────────────────────────────────────────────────┼─────────────────────────────────────────────╢
║ jwksPath                                              │ certs                                       ║
╟───────────────────────────────────────────────────────┼─────────────────────────────────────────────╢
║ clientAuthorizationUrl                                │                                             ║
╟───────────────────────────────────────────────────────┼─────────────────────────────────────────────╢
║ clientAuthorizationPath                               │ authorize-client                            ║
╟───────────────────────────────────────────────────────┼─────────────────────────────────────────────╢
║ clientAuthorizationView                               │ @app/views/authorize-client/authorize-clien ║
║                                                       │ t                                           ║
╟───────────────────────────────────────────────────────┼─────────────────────────────────────────────╢
║ openIdConnectUserinfoPath                             │ oidc/userinfo                               ║
╟───────────────────────────────────────────────────────┼─────────────────────────────────────────────╢
║ grantTypes                                            │ authorization_code, refresh_token           ║
╟───────────────────────────────────────────────────────┼─────────────────────────────────────────────╢
║ defaultAccessTokenTTL                                 │                                             ║
╟───────────────────────────────────────────────────────┼─────────────────────────────────────────────╢
║ resourceServerAccessTokenRevocationValidation         │ 1                                           ║
╟───────────────────────────────────────────────────────┼─────────────────────────────────────────────╢
║ enableOpenIdConnect                                   │ true                                        ║
╟───────────────────────────────────────────────────────┼─────────────────────────────────────────────╢
║ enableOpenIdConnectDiscovery                          │ true                                        ║
╟───────────────────────────────────────────────────────┼─────────────────────────────────────────────╢
║ openIdConnectDiscoveryIncludeSupportedGrantTypes      │ true                                        ║
╟───────────────────────────────────────────────────────┼─────────────────────────────────────────────╢
║ openIdConnectUserinfoEndpoint                         │ true                                        ║
╟───────────────────────────────────────────────────────┼─────────────────────────────────────────────╢
║ openIdConnectDiscoveryServiceDocumentationUrl         │                                             ║
╟───────────────────────────────────────────────────────┼─────────────────────────────────────────────╢
║ openIdConnectIssueRefreshTokenWithoutOfflineAccessSco │ false                                       ║
║ pe                                                    │                                             ║
╟───────────────────────────────────────────────────────┼─────────────────────────────────────────────╢
║ defaultUserAccountSelection                           │ 0                                           ║
╟───────────────────────────────────────────────────────┼─────────────────────────────────────────────╢
║ displayConfidentialExceptionMessages                  │ null                                        ║
╚═══════════════════════════════════════════════════════╧═════════════════════════════════════════════╝

Endpoints:
╔═════════════════════════╤═════════════════════════╤═══════════════════════════════════════════╗
║ Endpoint                │ URL                     │ Setting(s)                                ║
╟─────────────────────────┼─────────────────────────┼───────────────────────────────────────────╢
║ Authorize Client        │ oauth2/authorize        │ urlRulesPrefix, authorizePath             ║
╟─────────────────────────┼─────────────────────────┼───────────────────────────────────────────╢
║ Access Token            │ oauth2/access-token     │ urlRulesPrefix, accessTokenPath           ║
╟─────────────────────────┼─────────────────────────┼───────────────────────────────────────────╢
║ JSON Web Key Sets       │ oauth2/certs            │ urlRulesPrefix, jwksPath                  ║
╟─────────────────────────┼─────────────────────────┼───────────────────────────────────────────╢
║ Client Authorization    │ oauth2/authorize-client │ urlRulesPrefix, clientAuthorizationPath   ║
╟─────────────────────────┼─────────────────────────┼───────────────────────────────────────────╢
║ OpenId Connect Userinfo │ oauth2/oidc/userinfo    │ urlRulesPrefix, openIdConnectUserinfoPath ║
</pre>

**Comment by miltonlaufer** [comment]
Ok, I found the way. If anyone has the same problem, you need to configure your oauth2 module like this
```php

return [
    'class'                                                   => rhertogh\Yii2Oauth2Server\Oauth2Module::class,
    'identityClass'                                           => app\models\User::class,
     // ... etc
    /** THIS IS WHAT WAS MISSING */
    'openIdConnectIssueRefreshTokenWithoutOfflineAccessScope' => true,
    // ... etc 
    'grantTypes'                                              => [
        Oauth2Module::GRANT_TYPE_AUTH_CODE,
        Oauth2Module::GRANT_TYPE_REFRESH_TOKEN,
   ],
  // etc
];
```

Also, your identity class (`models/User.php`) has to implement this interface `Oauth2OidcUserSessionStatusInterface` and add this method:

```php
    public function hasActiveSession(): bool
    {
        return true;
    }
```

**Comment by rhertogh** [comment]
Thanks @miltonlaufer for the feedback.
I've updated the docs to include this info: https://github.com/rhertogh/yii2-oauth2-server/blob/master/docs/guide/start-openid-connect.md#openid-connect-and-oauth2-refresh-tokens
