### ISSUE TITLE
Add custom claim into access token

### ISSUE THREAD

**Issue by mecsu** [rhertogh/yii2-oauth2-server#20]
**Is your feature request related to a problem? Please describe.**

I have two use cases that need Authorization Server add custom claim into access token
1. Resource Server verify access token by issuer claim
2. Resource Server response data based on custom claim (related to identity)

I checked how to add  but can not.

**Describe the solution you'd like**
- Add configuration in module to enable add custom claims into access token

**Describe alternatives you've considered**
- For case verify token by issuer: can not find alternative, have to ignore issuer when verifying
- For case get data based on custom claim: Resource Server have to do extra task: query custom claim from data storage.  

**Additional context**

Below is content of access token fixed with these claims. I checked how to add custom claims but can not.
```
{
  "aud": "postman-sample-client",
  "jti": "48a98c6a849c1ff8b971965c31b6c17f25bac83d6427a1067089e14a93e70b40cacc061afc593a56",
  "iat": 1697700490.047131,
  "nbf": 1697700490.047134,
  "exp": 1697704090,
  "sub": "2632",
  "scopes": [
    "openid",
    "profile",
    "email"
  ]
}
```

**Comment by rhertogh** [comment]
Hi @mecsu,
The access token you showed contains "scopes". The OpenID Connect 'id token' will contain the "claims" (e.g. user properties).

Just to be sure, do you want to add "scopes" or "claims"?

**Comment by mecsu** [comment]
Hi @rhertogh,

Thanks for your reply. Actually, I need add custom claims (related to user) into access token.

**Comment by rhertogh** [comment]
Please note that in OpenID connect custom claims are never added to the "access_token", they are added to the "id_token".

To add a custom scope and claim you can add them to the module configuration:
https://github.com/rhertogh/yii2-oauth2-server/blob/0f534173a99d80187ed8127d56a582b9ee662631/sample/config/main.php#L97-L103

If configured properly they should show up in the `/.well-known/openid-configuration` endpoint,
e.g. http://your-host-name/.well-known/openid-configuration

![image](https://github.com/rhertogh/yii2-oauth2-server/assets/1292337/4442e5aa-6289-4968-a344-dba906ac92ea)


Next, add the scope to the database (most likely in a migration):
```php
// Create the custom scope
$scope = (new Oauth2Scope([
    'identifier' => 'my_custom_oidc_scope', // Should match the name in the module config
    'description' => 'A custom scope with custom claims', // A description
    'authorization_message' => 'Access custom user properties', // The message the end user will see
]))->persist();

// Link the custom scope to your client
(new Oauth2ClientScope([
    'client_id' => , // The id of your client
    'scope_id' => $scope->id,
]))->persist();
```

The final step is to add the property to the User model:
https://github.com/rhertogh/yii2-oauth2-server/blob/0f534173a99d80187ed8127d56a582b9ee662631/sample/models/User.php#L132-L135


Once configured your client can request the `my_custom_oidc_scope` scope (note that `openid` should also always be included), e.g. in Postman:

![image](https://github.com/rhertogh/yii2-oauth2-server/assets/1292337/18254124-214e-4e3a-8f78-b9b1e67011b2)

To test the content of the "id_token" you can copy the content from the response in Postman:
![image](https://github.com/rhertogh/yii2-oauth2-server/assets/1292337/25af4f71-cc58-414e-ab5f-2782da9e9062)

And paste it in a JWT reader, e.g. https://jwt.io/

![image](https://github.com/rhertogh/yii2-oauth2-server/assets/1292337/f2473ede-f93d-4525-9c07-58d3921ec375)

The custom claim will also show up in the OpenID Connect user info endpoint (`/oauth2/oidc/userinfo` by default):
![image](https://github.com/rhertogh/yii2-oauth2-server/assets/1292337/dfac083d-e1ca-40b9-8658-45c09e1fdc01)

**Comment by mecsu** [comment]
> Please note that in OpenID connect custom claims are never added to the "access_token", they are added to the "id_token".

Hi @rhertogh ,

I got it. I added custom scopes and claims in id_token before. Thank you.

**Comment by rhertogh** [comment]
Ah, Then I think I misunderstood you due to the `openid` scope.
Customizing the access token should in theory be possible (never tried it):

1. Create your own class that extends `\rhertogh\Yii2Oauth2Server\models\Oauth2AccessToken`
2. Overwrite the `\League\OAuth2\Server\Entities\Traits\AccessTokenTrait::convertToJWT()` function:
   ```php
   private function convertToJWT()
    {
        $this->initJwtConfiguration();

        return $this->jwtConfiguration->builder()
            ->permittedFor($this->getClient()->getIdentifier())
            ->identifiedBy($this->getIdentifier())
            ->issuedAt(new DateTimeImmutable())
            ->canOnlyBeUsedAfter(new DateTimeImmutable())
            ->expiresAt($this->getExpiryDateTime())
            ->relatedTo((string) $this->getUserIdentifier())
            ->withClaim('scopes', $this->getScopes())
            ->withClaim('my_custom_claim', 'my custom claim value') // 👈add custom claim(s)
            ->getToken($this->jwtConfiguration->signer(), $this->jwtConfiguration->signingKey());
    }
    ```
3. In your Yii config file configure the [Dependency Injection Container](https://www.yiiframework.com/doc/guide/2.0/en/concept-di-container) to use your own custom class:
    ```
    'container' => [
        'definitions' => [
            \rhertogh\Yii2Oauth2Server\interfaces\models\Oauth2AccessTokenInterface::class => YourCustomAccessToken::class,
        ],
    ],
    ```
