### ISSUE TITLE
Support Token Revocation

### ISSUE THREAD

**Issue by mecsu** [rhertogh/yii2-oauth2-server#21]
**Is your feature request related to a problem? Please describe.**
I need an endpoint to revoke token

**Describe the solution you'd like**
Follow this spec [RFC7009](https://datatracker.ietf.org/doc/html/rfc7009) to implement revocation endpoint

**Describe alternatives you've considered**
I have to extend this controller rhertogh\Yii2Oauth2Server\controllers\web\Oauth2ServerController, then implement new action Revoke

**Comment by rhertogh** [comment]
Hi @mecsu,
Thanks for the suggestion, please have a look at 305862a6
Could you test it on the `master` branch? The endpoint is available on `/oauth2/revoke` by default.

**Comment by mecsu** [comment]
Hi @rhertogh,

Thanks for implementing this feature. I have tested call endpoint /oauth2/revoke to revoke refresh_token but it return error:
`
{
    "error": "Bad Request",
    "error_description": "yii\\web\\BadRequestHttpException: Unable to resolve the `token` parameter to a valid token type ..."
}
`
And error message in log:
`
[error][rhertogh\Yii2Oauth2Server\controllers\web\server\Oauth2RevokeAction::parseTokenAsRefreshToken] The client specified the `token_type_hint` as "refresh_token", however the server is unable to parse the `token` as such: Defuse\Crypto\Exception\WrongKeyOrModifiedCiphertextException: Ciphertext has invalid hex encoding. in .../vendor/defuse/php-encryption/src/Crypto.php:311
`
Can you help check this issue?

**Comment by rhertogh** [comment]
@mecsu Could you send me the exact request body (for security, make sure the tokens in there are no longer valid)?

**Comment by mecsu** [comment]
Hi @rhertogh,

I tested revoke refresh_token successfully.

But I have tried revoke access_token, it return error:
`{ "error": "Bad Request", "error_description": "yii\\web\\BadRequestHttpException: Unable to resolve thetokenparameter to a valid token type ..." }`

I have debugged, found issue within function rhertogh\Yii2Oauth2Server\controllers\web\server\Oauth2RevokeAction::parseTokenAsAccessToken, it return ["clientIdentifier" => null].

```
protected function parseTokenAsAccessToken(Oauth2Module $module, string $token, string $tokenTypeHint)
    {
        try {
            ...
            $accessTokenClaims = $accessToken->claims();
            $accessTokenIdentifier = $accessTokenClaims->get('jti');
            // issue with below statement, cause no have claim "client_id"
            $clientIdentifier = $accessTokenClaims->get('client_id');

            return [
                'clientIdentifier' => $clientIdentifier,
                'accessTokenIdentifier' => $accessTokenIdentifier
            ];
        } catch (\Throwable $e) {
            if ($tokenTypeHint === 'access_token') {
                Yii::getLogger()->log(
                    'The client specified the `token_type_hint` as "access_token", however the server is unable to parse the `token` as such: ' . $e,
                    $module->getElaboratedHttpClientErrorsLogLevel(),
                    __METHOD__
                );
            }
            unset($e);
        }
        return null;
    }
```

**Comment by rhertogh** [comment]
@mecsu The `client_id` is a new claim in the access token. So any old access token won't include it. Does it work with a newly generated access token?

**Comment by mecsu** [comment]
> @mecsu The `client_id` is a new claim in the access token. So any old access token won't include it. Does it work with a newly generated access token?

Yes, it work with new access token. It's great. Many thanks.
