### ISSUE TITLE
Cannot install on Yii 2.0.47

### ISSUE THREAD

**Issue by ahmadfadlydziljalal** [rhertogh/yii2-oauth2-server#9]
➜  server composer require rhertogh/yii2-oauth2-server "*"     
./composer.json has been updated
Running composer update rhertogh/yii2-oauth2-server
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires rhertogh/yii2-oauth2-server *, found rhertogh/yii2-oauth2-server[dev-master, 1.0.0-alpha, ..., 1.0.0.x-dev (alias of dev-master)] but it does not match your minimum-stability.

**Comment by rhertogh** [comment]
Hi @ahmadfadlydziljalal,
Please note that the current release is still an alpha release. By default composer limits packages to stable releases.
You can change this behavior by adding the following to your `composer.json`:
```
{
  ...
  "minimum-stability": "dev",
  "prefer-stable": true,
  "require": {
    "yiisoft/yii2": "~2.0.47",
    ...
  }
}
```
You can find more info here:
https://getcomposer.org/doc/04-schema.md#minimum-stability
https://getcomposer.org/doc/04-schema.md#prefer-stable

**Comment by ahmadfadlydziljalal** [comment]
Thanks.
A little bit nervous if I deploy the app with this package in production. 
As you said, it's still in alpha release.
But, keep it this good work. Let me try first. 👍

**Comment by raimon-segura** [comment]
Hi!,

I've installed the last "unstable" version using the following comnand:
`composer require rhertogh/yii2-oauth2-server:dev-master`

By the way, @rhertogh When the extension will become an stable version?

Thanks!

**Comment by rhertogh** [comment]
@raimon-segura 
> By the way, @rhertogh When the extension will become an stable version?

There are still a few features and fixes I want to implement that might impact the database structure. After that the first stable release will be there. But this probably will still take a few months.

**Comment by rhertogh** [comment]
@raimon-segura Thanks for your supporting words.
I'll see if I can create some issues and milestones for the first stable release to provide more insight.

**Comment by raimon-segura** [comment]
Cool!... Many thanks!
